openapi: 3.0.3
info:
  title: legit-core
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://legit.test:8000'
paths:
  '/v1/projects/{project_id}/customers/post':
    post:
      summary: 'New Customer'
      operationId: newCustomer
      description: 'Add a new customer to the project'
      parameters: []
      responses:
        200:
          description: 'Customer created successfully!'
          content:
            application/json:
              schema:
                type: object
                example:
                  id: 9a136d5c-9336-4468-a85c-0e7863fc4c9c
                  name: Subhadeep
                  email: subhadeep+4@legit.is
                  thumb: null
                  wallet_connection: LEGIT_WALLET
                  address: '0x882e1C37B6D38258E21938561355ae513c9B365e'
                  custom_identifier: '12345678903'
                  metadata:
                    -
                      key: key1
                      value: value1
                    -
                      key: key2
                      value: value2
                  project_id: 99bb9d65-fb51-41b2-8cb2-21bcf680eb1b
                  created_at: '2023-09-07T10:24:58.000000Z'
                  updated_at: '2023-09-07T10:25:03.000000Z'
                  deleted_at: null
                properties:
                  id:
                    type: string
                    example: 9a136d5c-9336-4468-a85c-0e7863fc4c9c
                  name:
                    type: string
                    example: Subhadeep
                    description: 'The Name of the customer.'
                  email:
                    type: string
                    example: subhadeep+4@legit.is
                    description: 'The Email of the customer.'
                  thumb:
                    type: string
                    example: null
                    description: 'The Avatar of the customer.'
                  wallet_connection:
                    type: string
                    example: LEGIT_WALLET
                    description: 'The wallet connection type of the customer.'
                  address:
                    type: string
                    example: '0x882e1C37B6D38258E21938561355ae513c9B365e'
                    description: 'The wallet address of the customer.'
                  custom_identifier:
                    type: string
                    example: '12345678903'
                    description: 'The Custom Identifier of the customer in the organization.'
                  metadata:
                    type: array
                    example:
                      -
                        key: key1
                        value: value1
                      -
                        key: key2
                        value: value2
                    description: 'Metadata information.'
                    items:
                      type: object
                      properties:
                        key:
                          type: string
                          example: key1
                        value:
                          type: string
                          example: value1
                  project_id:
                    type: string
                    example: 99bb9d65-fb51-41b2-8cb2-21bcf680eb1b
                  created_at:
                    type: string
                    example: '2023-09-07T10:24:58.000000Z'
                  updated_at:
                    type: string
                    example: '2023-09-07T10:25:03.000000Z'
                  deleted_at:
                    type: string
                    example: null
        400:
          description: Unauthenticated!
          content:
            application/json:
              schema:
                type: object
                example:
                  status_code: 401
                  error_code: ERR401
                  message: 'Unauthorized to access this resource(s)'
                  data: Unauthenticated.
                properties:
                  status_code:
                    type: integer
                    example: 401
                  error_code:
                    type: string
                    example: ERR401
                  message:
                    type: string
                    example: 'Unauthorized to access this resource(s)'
                    description: 'Metadata information.'
                  data:
                    type: string
                    example: Unauthenticated.
      tags:
        - Global
      requestBody:
        required: false
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'The Name of the customer.'
                  example: commodi
                custom_identifier:
                  type: string
                  description: 'The Custom Identifier of the customer in the organization.'
                  example: iusto
                email:
                  type: string
                  description: 'The Email of the customer.'
                  example: anya24@example.org
                thumb:
                  type: string
                  format: binary
                  description: 'The Avatar of the customer.'
                metadata:
                  type: array
                  description: 'Customer information as Key-Value pair.'
                  example:
                    - []
                  items:
                    type: object
    parameters:
      -
        in: path
        name: project_id
        description: 'Optional parameter. The ID of the project'
        required: true
        schema:
          type: string
        examples:
          omitted:
            summary: 'When the value is omitted'
            value: ''
          present:
            summary: 'When the value is present'
            value: quae
tags:
  -
    name: Global
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
