/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Template } from "./template";
import { Expose, Type } from "class-transformer";

/**
 * NFT Schema
 */
export class Nft extends SpeakeasyBase {
    /**
     * Blockchain Address
     */
    @SpeakeasyMetadata()
    @Expose({ name: "address" })
    address?: string;

    /**
     * Balance
     */
    @SpeakeasyMetadata()
    @Expose({ name: "balance" })
    balance?: number;

    /**
     * This is the Badge NFT
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    /**
     * Token ID
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    /**
     * Last Updated at
     */
    @SpeakeasyMetadata()
    @Expose({ name: "last_updated" })
    lastUpdated?: string;

    /**
     * The Metadata Properties of the NFT
     */
    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    metadata?: string;

    /**
     * Name
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * Template model
     */
    @SpeakeasyMetadata()
    @Expose({ name: "template" })
    @Type(() => Template)
    template?: Template;
}
