/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * NFTUser Schema
 */
export class NFTUser extends SpeakeasyBase {
    /**
     * Blockchain Address
     */
    @SpeakeasyMetadata()
    @Expose({ name: "address" })
    address?: string;

    /**
     * Balance
     */
    @SpeakeasyMetadata()
    @Expose({ name: "balance" })
    balance?: number;

    /**
     * Created at
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    createdAt?: string;

    /**
     * Email
     */
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email?: string;

    /**
     * ID
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: any;

    /**
     * Name
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * Avatar of the customer
     */
    @SpeakeasyMetadata()
    @Expose({ name: "thumb" })
    thumb?: Uint8Array;
}
