/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Status of the Template
 */
export enum TemplateStatus {
    Active = "ACTIVE",
    Blocked = "BLOCKED",
}

/**
 * Wallet Connection of the Template
 */
export enum TemplateWalletConnection {
    LegitWallet = "LEGIT_WALLET",
}

/**
 * Template model
 */
export class Template extends SpeakeasyBase {
    /**
     * Blockchain Address
     */
    @SpeakeasyMetadata()
    @Expose({ name: "address" })
    address?: string;

    /**
     * Created at
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    createdAt?: string;

    /**
     * The Custom Identifier of the Template in the organization
     */
    @SpeakeasyMetadata()
    @Expose({ name: "custom_identifier" })
    customIdentifier?: string;

    /**
     * Deleted at
     */
    @SpeakeasyMetadata()
    @Expose({ name: "deleted_at" })
    deletedAt?: string;

    /**
     * Email
     */
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email?: string;

    /**
     * ID
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: any;

    /**
     * The Metadata Properties of the Template in the organization
     */
    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    metadata?: string;

    /**
     * Name
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * Project ID
     */
    @SpeakeasyMetadata()
    @Expose({ name: "project_id" })
    projectId?: number;

    /**
     * Status of the Template
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: TemplateStatus;

    /**
     * Avatar of the Template
     */
    @SpeakeasyMetadata()
    @Expose({ name: "thumb" })
    thumb?: Uint8Array;

    /**
     * Updated at
     */
    @SpeakeasyMetadata()
    @Expose({ name: "updated_at" })
    updatedAt?: string;

    /**
     * Wallet Connection of the Template
     */
    @SpeakeasyMetadata()
    @Expose({ name: "wallet_connection" })
    walletConnection?: TemplateWalletConnection;
}
