/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Update Customer body data
 */
export class UpdateCustomer extends SpeakeasyBase {
    /**
     * The Custom Identifier of the customer in the organization
     */
    @SpeakeasyMetadata()
    @Expose({ name: "custom_identifier" })
    customIdentifier?: string;

    /**
     * Email
     */
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email?: string;

    /**
     * The Metadata Properties of the customer in the organization
     */
    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    metadata?: string;

    /**
     * Name
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * Avatar of the customer
     */
    @SpeakeasyMetadata()
    @Expose({ name: "thumb" })
    thumb?: Uint8Array;
}
