/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class NewCustomerRequestBodyMetadata extends SpeakeasyBase {}

export class NewCustomerRequestBodyThumb extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "multipart_form, content=true" })
    content: Uint8Array;

    @SpeakeasyMetadata({ data: "multipart_form, name=thumb" })
    thumb: string;
}

export class NewCustomerRequestBody extends SpeakeasyBase {
    /**
     * The Custom Identifier of the customer in the organization.
     */
    @SpeakeasyMetadata({ data: "multipart_form, name=custom_identifier" })
    customIdentifier?: string;

    /**
     * The Email of the customer.
     */
    @SpeakeasyMetadata({ data: "multipart_form, name=email" })
    email?: string;

    /**
     * Customer information as Key-Value pair.
     */
    @SpeakeasyMetadata({
        data: "multipart_form, name=metadata;json=true",
        elemType: NewCustomerRequestBodyMetadata,
    })
    metadata?: NewCustomerRequestBodyMetadata[];

    /**
     * The Name of the customer.
     */
    @SpeakeasyMetadata({ data: "multipart_form, name=name" })
    name?: string;

    /**
     * The Avatar of the customer.
     */
    @SpeakeasyMetadata({ data: "multipart_form, file=true" })
    thumb?: NewCustomerRequestBodyThumb;
}

export class NewCustomerRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=multipart/form-data" })
    requestBody?: NewCustomerRequestBody;

    /**
     * The ID of the project.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=project_id" })
    projectId: string;
}

export class NewCustomer200ApplicationJSONMetadata extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "key" })
    key?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value?: string;
}

/**
 * Customer created successfully!
 */
export class NewCustomer200ApplicationJSON extends SpeakeasyBase {
    /**
     * The wallet address of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "address" })
    address?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    createdAt?: string;

    /**
     * The Custom Identifier of the customer in the organization.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "custom_identifier" })
    customIdentifier?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "deleted_at" })
    deletedAt?: string;

    /**
     * The Email of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * Metadata information.
     */
    @SpeakeasyMetadata({ elemType: NewCustomer200ApplicationJSONMetadata })
    @Expose({ name: "metadata" })
    @Type(() => NewCustomer200ApplicationJSONMetadata)
    metadata?: NewCustomer200ApplicationJSONMetadata[];

    /**
     * The Name of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "project_id" })
    projectId?: string;

    /**
     * The Avatar of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "thumb" })
    thumb?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "updated_at" })
    updatedAt?: string;

    /**
     * The wallet connection type of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "wallet_connection" })
    walletConnection?: string;
}

export class NewCustomerResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Customer created successfully!
     */
    @SpeakeasyMetadata()
    newCustomer200ApplicationJSONObject?: NewCustomer200ApplicationJSON;
}
