/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class PostV1TransactionsTransactionIdCancelRequest extends SpeakeasyBase {
    /**
     * The ID of the transaction.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=transaction_id" })
    transactionId: string;
}

export class PostV1TransactionsTransactionIdCancelResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
