/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class PostV1TemplatesTemplateIdPlaygroundTransactionsPayloadFunctionNameRequestBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "function_name" })
    functionName: string;
}

export class PostV1TemplatesTemplateIdPlaygroundTransactionsPayloadFunctionNameRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    requestBody: PostV1TemplatesTemplateIdPlaygroundTransactionsPayloadFunctionNameRequestBody;

    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=function_name" })
    functionName: string;

    /**
     * The ID of the template.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=template_id" })
    templateId: string;
}

export class PostV1TemplatesTemplateIdPlaygroundTransactionsPayloadFunctionNameResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
