/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class PostV1UploadToIpfsRequestBodyFile extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "multipart_form, content=true" })
    content: Uint8Array;

    @SpeakeasyMetadata({ data: "multipart_form, name=file" })
    file: string;
}

export class PostV1UploadToIpfsRequestBody extends SpeakeasyBase {
    /**
     * Must be an image. Must not be greater than 5120 kilobytes.
     */
    @SpeakeasyMetadata({ data: "multipart_form, file=true" })
    file?: PostV1UploadToIpfsRequestBodyFile;
}

export class PostV1UploadToIpfsResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
