/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class PutV1CustomersCustomerIdRequestBodyThumb extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "multipart_form, content=true" })
    content: Uint8Array;

    @SpeakeasyMetadata({ data: "multipart_form, name=thumb" })
    thumb: string;
}

export class PutV1CustomersCustomerIdRequestBody extends SpeakeasyBase {
    /**
     * Must be at least 1 character. Must not be greater than 255 characters.
     */
    @SpeakeasyMetadata({ data: "multipart_form, name=custom_identifier" })
    customIdentifier?: string;

    /**
     * Must be a valid email address.
     */
    @SpeakeasyMetadata({ data: "multipart_form, name=email" })
    email?: string;

    /**
     * Must be at least 1 character. Must not be greater than 32 characters.
     */
    @SpeakeasyMetadata({ data: "multipart_form, name=name" })
    name?: string;

    /**
     * Must be an image. Must not be greater than 5120 kilobytes.
     */
    @SpeakeasyMetadata({ data: "multipart_form, file=true" })
    thumb?: PutV1CustomersCustomerIdRequestBodyThumb;
}

export class PutV1CustomersCustomerIdRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=multipart/form-data" })
    requestBody?: PutV1CustomersCustomerIdRequestBody;

    /**
     * The ID of the customer.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=customer_id" })
    customerId: string;
}

export class PutV1CustomersCustomerIdResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
